"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = 'login'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2o8g%9l1+5t-ru@4cq1&+s24(n-%7w3(c*-jtk&6+o!_@*$$_1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    "accounts",
    "csp",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "bookshelf.CustomUser"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



# SECURITY (core)
# ----------------
# Development: keep DEBUG True only locally. Production must be False.
DEBUG = False   # <--- PRODUCTION: set to False

# Use environment variable for secret in production
import os
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-for-local")

# Allowed hosts: set to your domain(s) in production
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1").split()

# ----------------
# Cookie & session security
# ----------------
# Ensure cookies are only sent over HTTPS in production:
SESSION_COOKIE_SECURE = True        # production-only (requires HTTPS)
CSRF_COOKIE_SECURE = True           # production-only (requires HTTPS)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False        # usually False so JS libraries can read (keep default unless needed)

# ----------------
# Browser-side protections
# ----------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"            # prevents clickjacking

# ----------------
# HSTS & SSL redirect (production-only)
# ----------------
SECURE_SSL_REDIRECT = True          # production-only (requires HTTPS)
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7   # 1 week; increase in long-term production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = False         # set True only after verifying

# ----------------
# Other useful settings
# ----------------
# Limit host header sizes and such if needed; keep defaults otherwise

# ----------------
# Static & media (ensure correct settings for production)
# ----------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ----------------
# Content Security Policy (if using django-csp middleware)
# Add the CSP middleware to MIDDLEWARE (see below)
# ----------------
# Example CSP (strict-ish) - adjust to your allowed domains
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'",),
        "style-src": ("'self'", "'unsafe-inline'"),
        "img-src": ("'self'", "data:"),
        "font-src": ("'self'", "data:"),
    }
}


# =========================
# HTTPS & Security Settings
# =========================

import os

# Use environment variables for production secrets and toggles
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# IMPORTANT: set this to your domain(s) in production, e.g. "example.com"
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1").split()

# Secret key must be loaded from an environment variable in production
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key")

# Redirect all HTTP requests to HTTPS.
# Production: True (requires HTTPS to be available). For local dev, set False.
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True") == "True"

# HTTP Strict Transport Security (HSTS)
# Instruct browsers to access site only over HTTPS for the given seconds.
# Example: 31536000 = 1 year. Only enable long durations after you are sure HTTPS works.
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True") == "True"
SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "True") == "True"

# Secure cookies: only transmit cookies over HTTPS
SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "True") == "True"
CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "True") == "True"

# Other browser security headers
X_FRAME_OPTIONS = "DENY"                 # prevents clickjacking by disallowing framing
SECURE_CONTENT_TYPE_NOSNIFF = True       # prevents MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True         # enables browser's XSS filter

# If Django is behind a trusted proxy/load balancer (e.g. nginx, ELB)
# and that proxy sets X-Forwarded-Proto, configure this so Django knows the request was HTTPS.
# Example: ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional: ensure SESSION_COOKIE_HTTPONLY to prevent JS access to session cookie
SESSION_COOKIE_HTTPONLY = True

